### ISSUE TITLE
Can not tap edge Area

### ISSUE THREAD

**Issue by yonce3** [yonce3/Ocero#2]
## OverView
端の列をタップするとクラッシュする

## Cause
```
2021-03-19 15:33:06.262 11275-11275/? E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=73; index=-4
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.yonce3.ocero.Board.checkCell(Board.kt:54)
        at com.yonce3.ocero.view.CustomBoardView.onTouchEvent(CustomBoardView.kt:134)
```

**Comment by yonce3** [comment]
Fixed
